"""
Django settings for matchmate project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env 
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)kg2p*tya+&4ug(&%v75rj(50k%er%_j^h0z%+dtc*)c#csvbf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.18.214',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'DESKTOP-824PRP9',
    'desktop-824prp9',
    '192.168.18.71:5175',
    '44.220.158.223',
    'mmate.website',  # Your GoDaddy domain
]
# Add domain from environment variable if set
if os.getenv('DOMAIN_NAME'):
    ALLOWED_HOSTS.extend([domain.strip() for domain in os.getenv('DOMAIN_NAME').split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
     'corsheaders',
    'matching_app.apps.MatchingAppConfig',
]

MIDDLEWARE = [
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'matchmate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'matchmate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Matchmate',
        'USER': 'postgres',
        'PASSWORD': 'abbas123',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Upload Settings - Remove size restrictions
# Allow uploads of any size (set to 500MB to effectively remove restriction)
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB in bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB in bytes
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase field limit

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Email configuration (Gmail SMTP)
EMAIL_BACKEND = 'matching_app.email_backends.GmailEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'shamraizb7@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'ijvl nnug whbl pswd')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)







OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')  # required for AI profile text + CNIC OCR

# Zoom API Configuration
ZOOM_ACCOUNT_ID = os.getenv('ZOOM_ACCOUNT_ID')
ZOOM_CLIENT_ID = os.getenv('ZOOM_CLIENT_ID')
ZOOM_CLIENT_SECRET = os.getenv('ZOOM_CLIENT_SECRET')
ZOOM_BASE_URL = 'https://api.zoom.us/v2'
ZOOM_OAUTH_URL = 'https://zoom.us/oauth/token'

# Google OAuth Configuration
# Set this to your production server URL (with protocol) if different from request host
# Example: 'http://yourdomain.com' or 'https://api.yourdomain.com'
# IMPORTANT: Use HTTP if you don't have SSL certificate, HTTPS if you do
# If not set, will use request.build_absolute_uri() to determine dynamically
GOOGLE_OAUTH_REDIRECT_BASE_URL = os.getenv('GOOGLE_OAUTH_REDIRECT_BASE_URL', 'http://mmate.website')

# Zoom SDK Configuration (for Mobile SDK integration)
# These are DIFFERENT from OAuth credentials - get from Zoom Marketplace > Your App > SDK Credentials
ZOOM_SDK_KEY = os.getenv('ZOOM_SDK_KEY')
ZOOM_SDK_SECRET = os.getenv('ZOOM_SDK_SECRET')

# Report System Configuration
REPORT_DISABLE_THRESHOLD = int(os.getenv('REPORT_DISABLE_THRESHOLD', '5'))  # Number of distinct reports needed to disable profile
REPORT_STATUS_PENDING = 'pending'
REPORT_STATUS_REVIEWED = 'reviewed'
REPORT_STATUS_DISMISSED = 'dismissed'

# Firebase Cloud Messaging (FCM) Configuration
# Option 1: Path to service account JSON file (recommended for production)
FIREBASE_SERVICE_ACCOUNT_PATH = os.getenv(
    'FIREBASE_SERVICE_ACCOUNT_PATH',
    BASE_DIR / 'match-mate-cb4e2-firebase-adminsdk-fbsvc-38a701b9e7.json'  # Your Firebase service account file
)

# Option 2: Service account JSON content as string (alternative)
# You can set FIREBASE_SERVICE_ACCOUNT_JSON in .env file with the JSON content
# FIREBASE_SERVICE_ACCOUNT_JSON = os.getenv('FIREBASE_SERVICE_ACCOUNT_JSON', None)