from django.urls import include, path

from .views import (
    ChangePasswordView,
    CNICVerificationView,
    DeviceDeactivateView,
    DeviceListView,
    DeviceRegisterView,
    LoginView,
    MatchPreferenceView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileDescriptionView,
    ProfileImageDeleteView,
    ProfileImagesUploadView,
    ProfileListView,
    ProfilePhotoUploadView,
    ProfileSearchView,
    RegistrationView,
    SubscriptionCancelView,
    SubscriptionPlanListView,
    SubscriptionUsageView,
    SupportRequestView,
    UserAccountDeleteView,
    UserAccountView,
    UserProfileDetailView,
    UserProfileView,
    UserReportView,
    UserSubscriptionView,
)


urlpatterns = [
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('account/', UserAccountView.as_view(), name='account'),
    path('account/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('account/delete/', UserAccountDeleteView.as_view(), name='account-delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/<int:user_id>/', UserProfileDetailView.as_view(), name='profile-detail'),
    path(
        'profile/description/',
        ProfileDescriptionView.as_view(),
        name='profile-description',
    ),
    path('profile/photo/', ProfilePhotoUploadView.as_view(), name='profile-photo'),
    path('profile/images/', ProfileImagesUploadView.as_view(), name='profile-images'),
    path('profile/images/<int:image_id>/', ProfileImageDeleteView.as_view(), name='profile-image-delete'),
    path('cnic/verify/', CNICVerificationView.as_view(), name='cnic-verify'),
    path('preferences/', MatchPreferenceView.as_view(), name='match-preferences'),
    path('profiles/', ProfileListView.as_view(), name='profile-list'),
    path('profiles/search/', ProfileSearchView.as_view(), name='profile-search'),
    path('reports/', UserReportView.as_view(), name='user-report'),
    path('subscriptions/plans/', SubscriptionPlanListView.as_view(), name='subscription-plans'),
    path('subscriptions/', UserSubscriptionView.as_view(), name='user-subscription'),
    path('subscriptions/usage/', SubscriptionUsageView.as_view(), name='subscription-usage'),
    path('subscriptions/cancel/', SubscriptionCancelView.as_view(), name='subscription-cancel'),
    path('v1/connections/', include('matching_app.urls_connections')),
    path('v1/messages/', include('matching_app.urls_messages')),
    path('v1/sessions/', include('matching_app.urls_sessions')),
    path('devices/register/', DeviceRegisterView.as_view(), name='device-register'),
    path('devices/', DeviceListView.as_view(), name='device-list'),
    path('devices/deactivate/', DeviceDeactivateView.as_view(), name='device-deactivate'),
    path('support/', SupportRequestView.as_view(), name='support-request'),
    # User and Report management ViewSets (production-ready REST APIs)
    path('manage/', include('matching_app.urls_users_reports')),
]

