# Generated by Django 4.1.13 on 2025-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
