# Generated by Django 4.1.13 on 2025-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0004_userprofile_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='caste',
            field=models.CharField(blank=True, choices=[('Syed', 'Syed'), ('Mughal', 'Mughal'), ('Rajput', 'Rajput'), ('Arain', 'Arain'), ('Jatt', 'Jatt'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Rawalpindi', 'Rawalpindi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('Pakistan', 'Pakistan'), ('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('UAE', 'UAE'), ('Saudi Arabia', 'Saudi Arabia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Diploma', 'Diploma')], max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Employed', 'Employed'), ('Home-maker', 'Home-maker'), ('Retired', 'Retired'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widower', 'Widower')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Business', 'Business'), ('IT Professional', 'IT Professional'), ('Accountant', 'Accountant'), ('Lawyer', 'Lawyer'), ('Other', 'Other')], max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_for',
            field=models.CharField(blank=True, choices=[('Myself', 'Myself'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sect',
            field=models.CharField(blank=True, choices=[('Sunni', 'Sunni'), ('Shia', 'Shia'), ('Ahle Hadith', 'Ahle Hadith'), ('Deobandi', 'Deobandi'), ('Barelvi', 'Barelvi')], max_length=100),
        ),
    ]
