# Generated by Django 5.2.8 on 2025-11-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0011_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_meeting_url', models.URLField(blank=True, null=True)),
                ('zoom_meeting_password', models.CharField(blank=True, max_length=100, null=True)),
                ('initiator_ready', models.BooleanField(default=False)),
                ('participant_ready', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_initiated', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_participated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Session Created'), ('started', 'Session Started'), ('ready', 'Participant Ready'), ('joined', 'Participant Joined'), ('left', 'Participant Left'), ('ended', 'Session Ended'), ('cancelled', 'Session Cancelled'), ('zoom_link_generated', 'Zoom Link Generated')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='matching_app.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionJoinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_tokens', to='matching_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_join_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['initiator', 'status', '-created_at'], name='matching_ap_initiat_4746e7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['participant', 'status', '-created_at'], name='matching_ap_partici_d8c795_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', '-created_at'], name='matching_ap_status_800188_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('initiator', models.F('participant')), _negated=True), name='prevent_self_session'),
        ),
        migrations.AddIndex(
            model_name='sessionauditlog',
            index=models.Index(fields=['session', '-created_at'], name='matching_ap_session_b4bcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionauditlog',
            index=models.Index(fields=['user', '-created_at'], name='matching_ap_user_id_9c8b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionauditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='matching_ap_event_t_8d2e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionjointoken',
            index=models.Index(fields=['token', 'is_used'], name='matching_ap_token_d44fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionjointoken',
            index=models.Index(fields=['session', 'user', 'is_used'], name='matching_ap_session_e441ab_idx'),
        ),
    ]
