# Generated by Django 5.2.8 on 2025-12-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0014_userprofile_disabled_at_userprofile_disabled_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], help_text='Subscription tier level', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for the subscription plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this plan includes')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price (0.00 for free tier)', max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Duration of subscription in days')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available for subscription')),
                ('max_profile_views', models.IntegerField(default=-1, help_text='Maximum profile views per month (-1 for unlimited)')),
                ('max_connections', models.IntegerField(default=-1, help_text='Maximum connections per month (-1 for unlimited)')),
                ('can_send_messages', models.BooleanField(default=True, help_text='Can send messages to connections')),
                ('can_view_photos', models.BooleanField(default=True, help_text='Can view profile photos')),
                ('can_see_who_viewed', models.BooleanField(default=False, help_text='Can see who viewed their profile')),
                ('priority_support', models.BooleanField(default=False, help_text='Priority customer support')),
                ('advanced_search', models.BooleanField(default=False, help_text='Access to advanced search filters')),
                ('verified_badge', models.BooleanField(default=False, help_text='Verified badge on profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', help_text='Current subscription status', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription started')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the subscription expires (null for lifetime/free)', null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether subscription auto-renews')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('profile_views_used', models.IntegerField(default=0, help_text='Number of profile views used in current period')),
                ('connections_used', models.IntegerField(default=0, help_text='Number of connections used in current period')),
                ('last_reset_at', models.DateTimeField(auto_now_add=True, help_text='When usage counters were last reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='matching_app.subscriptionplan')),
                ('user', models.OneToOneField(help_text='User who has this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='matching_ap_user_id_43073b_idx'), models.Index(fields=['status', 'expires_at'], name='matching_ap_status_4378fc_idx')],
            },
        ),
    ]
