# Generated by Django 5.2.8 on 2025-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0015_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_chat_users',
            field=models.IntegerField(default=-1, help_text='Maximum number of different users you can chat with (-1 for unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_connection_requests',
            field=models.IntegerField(default=-1, help_text='Maximum connection requests per month (-1 for unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_sessions',
            field=models.IntegerField(default=-1, help_text='Maximum number of call sessions per month (-1 for unlimited)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='chat_users_count',
            field=models.IntegerField(default=0, help_text='Number of different users user has chatted with'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='connection_requests_used',
            field=models.IntegerField(default=0, help_text='Number of connection requests sent in current period'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='sessions_used',
            field=models.IntegerField(default=0, help_text='Number of call sessions created in current period'),
        ),
    ]
