# Generated by Django 5.2.8 on 2025-12-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0016_subscriptionplan_max_chat_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Profile image file', upload_to='profiles/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order/position of image (for sorting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(help_text='Profile that owns this image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matching_app.userprofile')),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
