# Generated by Django 5.2.8 on 2025-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0017_add_user_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree_title',
            field=models.CharField(blank=True, help_text='Title of the degree obtained', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of education (e.g., "2018-2022" or "4 years")', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institute_name',
            field=models.CharField(blank=True, help_text='Name of the educational institute', max_length=255),
        ),
    ]
