# Generated by Django 5.2.8 on 2025-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0018_add_education_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_country',
            field=models.CharField(blank=True, choices=[('Pakistan', 'Pakistan'), ('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('UAE', 'UAE'), ('Saudi Arabia', 'Saudi Arabia')], help_text='Country where the user was born', max_length=100),
        ),
    ]
