# Generated by Django 5.2.8 on 2025-12-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0019_add_birth_country_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_country',
            field=models.CharField(blank=True, help_text='Country where the user was born', max_length=100),
        ),
    ]
