# Generated by Django 5.2.8 on 2025-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0020_remove_birth_country_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for reporting the user', max_length=50),
        ),
    ]
