# Generated by Django 5.2.8 on 2025-12-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0021_remove_report_reason_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(db_index=True, help_text='Firebase Cloud Messaging token for this device', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], help_text='Type of device (Android or iOS)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device token is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='matching_ap_user_id_cbd67c_idx'), models.Index(fields=['fcm_token', 'is_active'], name='matching_ap_fcm_tok_7f9454_idx')],
            },
        ),
    ]
