# Generated by Django 5.2.8 on 2026-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0023_alter_matchpreference_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Admin verification status. Profile shows 95% until admin verifies, then 100%.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
