# Generated by Django 5.2.8 on 2026-01-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0024_add_admin_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(db_index=True, help_text='Firebase Cloud Messaging token for this device', max_length=255),
        ),
    ]
