# Generated by Django 5.2.8 on 2026-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0025_remove_fcm_token_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user reporting the issue', max_length=254)),
                ('problem_description', models.TextField(help_text='Description of the problem or issue reported by the user')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', help_text='Current status of the support request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the support request was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='matching_ap_email_ab388d_idx'), models.Index(fields=['status', '-created_at'], name='matching_ap_status_bc44c3_idx')],
            },
        ),
    ]
