# Generated by Django 6.0.1 on 2026-01-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0027_add_google_oauth_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googleoauthtoken',
            new_name='matching_ap_user_id_8efd5c_idx',
            old_name='matching_ap_user_id_abc123_idx',
        ),
    ]
