# Generated by Django 6.0.1 on 2026-01-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0029_add_google_meet_fields_to_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='zoom_meeting_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='zoom_meeting_password',
        ),
        migrations.RemoveField(
            model_name='session',
            name='zoom_meeting_url',
        ),
        migrations.AlterField(
            model_name='session',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='User who generated the meeting link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
